### ISSUE TITLE
todo:[Select] implement batch loading of request data or other bottoming out behaviors

### ISSUE THREAD

**Issue by RSS1102** [shuimo-design/shuimo-ui#47]
**Requirement:**
 Multiple fixed data requests can be made using the `Select` component.

**Implementation:**

1. Expose a method called `touchBottom` that is triggered when it bottoms out - used to customize events for users when it bottoms out. (Optional)
2. Expose an optional parameter `touchBottomDistance` - used to allow users to customize the bottom distance and include a default distance. (Optional)

**Comment by higuaifan** [comment]
1. Use `fetch` to achieve the `touchBottom` requirement, and their logics are the same, but `fetch` feels more comfortable as the property name.
2. `touchBottomDistance` doesn't seem to be necessary. The original intention is to trigger the `loading` state and request data when reaching the bottom. So, having the `loading` state triggered when reaching the bottom is sufficient.
3. A `needFetch` prop is provided.

The overall solution is in the `beta` version for trial. Let's try it out first, and if there are any issues, we can discuss further🐶

-------

1. 用`fetch`来实现`touchBottom`的需求，并且他们的逻辑也是相同的，不过感觉`fetch`这个属性名更舒服点；
2. `touchBottomDistance`感觉没什么需要的场景，本意就是触及底部后`loading`然后请求数据，那其实只要触底后`loading`状态就好了；
3. 提供了一个`needFetch`prop；

整体方案是一个`beta`版本，先试用一下，有什么问题再讨论🐶
