### ISSUE TITLE
后续会考虑对React的支持吗

### ISSUE THREAD

**Issue by Muzych** [shuimo-design/shuimo-ui#61]
如题

**Comment by higuaifan** [comment]
奥！如果有需要的话，我们也可以更改计划，将它提前一点，马上新建仓库的🐶

**Comment by Muzych** [comment]
> 奥！如果有需要的话，我们也可以更改计划，将它提前一点，马上新建仓库的🐶

我正在学习React，我想为你们的React推进作一些贡献，但是我还没有接触过如何构建组件库。

**Comment by higuaifan** [comment]
> > 奥！如果有需要的话，我们也可以更改计划，将它提前一点，马上新建仓库的🐶
> 
> 我正在学习React，我想为你们的React推进作一些贡献，但是我还没有接触过如何构建组件库。

非常欢迎！
构建组件库的逻辑其实并不复杂，可以参考一些大的组件库。
有需要的话，可以在[discord](https://discord.com/invite/xy3BenWvYj) 这里找到我，
或者我们通过邮箱：
<a href="mailto:higuaifan@higuaifan.com">higuaifan@higuaifan.com</a> 
 交换下微信？
