### ISSUE TITLE
[🐞 bug] The content at the bottom of the document is not fully displayed

### ISSUE THREAD

**Issue by QJvic** [shuimo-design/shuimo-ui#69]
# 🐞 Bug Report

> 请尽可能使用英文描述问题，或者是提供中英文双语描述（机翻也没有关系），便于后来者检索问题。

**If you are absolutely certain that this is a `bug` and you are able and willing to submit a `PR`, please do so.**

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of the code available.

## 📢 Describe the bug

文档网页，当浏览器窗口高度小时，文档最下方内容显示不全。

In document webpage, when the browser window height is small, the content at the bottom of the document is not fully displayed.

![image](https://github.com/shuimo-design/shuimo-ui/assets/17841191/8ba3f685-fe81-47cf-8c9c-88dff6f55c59)

**Comment by higuaifan** [comment]
doc页面正在筹备改版，同时目录在过屏幕小时其实也会显示错误，以及移动端的显示也非常不友好。

无落如何感谢您的喜欢和`pr`，期待能与您有更多交流。


The doc page is in preparation for a revision. At the same time, the "Menu" will actually display an error when the screen is too small, and the display on the mobile terminal is also very unfriendly.

Thank you very much for your likes and PRs, and I look forward to having more interactions with you.

**Comment by QJvic** [comment]
> `doc`页面正在筹备改版，同时目录在过屏幕小时其实也会显示错误，以及移动端的显示也非常不友好。
> 
> 无落如何感谢您的喜欢和`pr`，期待能与您有更多交流。
> 
> The `doc` page is in preparation for a revision. At the same time, the "Menu" will actually display an error when the screen is too small, and the display on the mobile terminal is also very unfriendly.
> 
> Thank you very much for your likes and `PR`, and I look forward to having more interactions with you.

好的，今天也发现了移动端的显示问题。本来准备明天和切换组件文档，滚动条不重回顶部的问题一起提pr的，那先不提了。By the way，确实是让人眼前一亮的UI。😋

**Comment by higuaifan** [comment]
> > `doc`页面正在筹备改版，同时目录在过屏幕小时其实也会显示错误，以及移动端的显示也非常不友好。
> > 无落如何感谢您的喜欢和`pr`，期待能与您有更多交流。
> > The `doc` page is in preparation for a revision. At the same time, the "Menu" will actually display an error when the screen is too small, and the display on the mobile terminal is also very unfriendly.
> > Thank you very much for your likes and `PR`, and I look forward to having more interactions with you.
> 
> 好的，今天也发现了移动端的显示问题。本来准备明天和切换组件文档滚动条不重回顶部的问题一起提pr的，那先不提了。By the way，确实是让人眼前一亮的UI。😋

欢迎pr！！
doc的改版还处于UI新建文件夹的状态，需要大量的时间，短期内应该不太能上线，当前版本doc存在的能不改办修复的问题仍然需要修复。
By the way, 何不点个小小的star🌟 🐶。
