### ISSUE TITLE
[🐞 Datepicker] has inner scrollBar

### ISSUE THREAD

**Issue by QJvic** [shuimo-design/shuimo-ui#75]
# 🐞 Bug Report

> 请尽可能使用英文描述问题，或者是提供中英文双语描述（机翻也没有关系），便于后来者检索问题。

**If you are absolutely certain that this is a `bug` and you are able and willing to submit a `PR`, please do so.**

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of the code available.

## 📢 Describe the bug

 Datepicker has inner scrollBar

<img width="450" alt="image" src="https://github.com/shuimo-design/shuimo-ui/assets/17841191/f752fad4-5fd5-47b9-8295-1c97428dc3d8">

**Comment by higuaifan** [comment]
Fixed In :  https://github.com/shuimo-design/shuimo-ui/commit/13377d3541b78b2f0848299ab0efaa60f1a312d5

**Comment by QJvic** [comment]
> Fixed In : [13377d3](https://github.com/shuimo-design/shuimo-ui/commit/13377d3541b78b2f0848299ab0efaa60f1a312d5)

Maybe this is not the best solution. For example, when we use datePicker and input in a same row, they have different height (the height of input box is 32px).

**Comment by higuaifan** [comment]
> > Fixed In : [13377d3](https://github.com/shuimo-design/shuimo-ui/commit/13377d3541b78b2f0848299ab0efaa60f1a312d5)
> 
> Maybe this is not the best solution. For example, when we use datePicker and input in a same row, they have different height (the height of input box is 32px).

Yes, you are right. 
The `CSS` of some components is quite outdated. Although it has been refactored several times, the original code is about 3 years ago.
You must have noticed, In the current structure, I have to explicitly set the `height` and `width`, which was a notion I didn't think would require so much compatibility when the project was just init. 
especially with "input-related" components such as `select` and `datePicker`, that they all have this kind of issue.
But! We have relevant plans: https://github.com/shuimo-design/shuimo-ui/issues/64
> Non-essential  : organizing all css, mainly streamlining variables, considering a more elegant way of writing;
So relatively speaking, this falls under a 'temporary solution'.

**If you have any ideas or suggestions, please make sure to raise them. We really need some discussion!**

**Comment by QJvic** [comment]
> > > Fixed In : [13377d3](https://github.com/shuimo-design/shuimo-ui/commit/13377d3541b78b2f0848299ab0efaa60f1a312d5)
> > 
> > 
> > Maybe this is not the best solution. For example, when we use datePicker and input in a same row, they have different height (the height of input box is 32px).
> 
> Yes, you are right. The `CSS` of some components is quite outdated. Although it has been refactored several times, the original code is about 3 years ago. You must have noticed, In the current structure, I have to explicitly set the `height` and `width`, which was a notion I didn't think would require so much compatibility when the project was just init. especially with "input-related" components such as `select` and `datePicker`, that they all have this kind of issue. But! We have relevant plans: #64
> 
> > Non-essential  : organizing all css, mainly streamlining variables, considering a more elegant way of writing;
> > So relatively speaking, this falls under a 'temporary solution'.
> 
> **If you have any ideas or suggestions, please make sure to raise them. We really need some discussion!**

As far as this issue is concerned, I think it's more appropriate to set the `overflow` of the wrap box to `hidden` than to modify the height.

**Comment by higuaifan** [comment]
> As far as this issue is concerned, I think it's more appropriate to set the `overflow` of the wrap box to `hidden` than to modify the height.

In some of my ancient memories, hiding inputs with overflow feels like `"playing hooky"`, potentially causing issues in certain scenarios. However, I've tested several scenarios and it seems there are no problems. 
Anyway, your solution is better and more elegant; 
I fixed it.
