### ISSUE TITLE
💬 [Communicate] Do we need to differentiate the branch between `dev` or `publish` ？

### ISSUE THREAD

**Issue by youuss** [shuimo-design/shuimo-ui#78]
# 💬 Communicate

we do everything on the `main` branch。But when someone fork this rep，all actions of `main` branch will be forked. This will cause some unnecessary mistakes like this(https://github.com/youuss/shuimo-ui/actions)
![image](https://github.com/shuimo-design/shuimo-ui/assets/34266177/c84439aa-e33d-4492-ab28-5de2283c9af6)

> so i think we should differentiate the `dev` and `publish` branch？ @RSS1102

**Comment by higuaifan** [comment]
Add `check repository steps` or remove this action , use CI like `TeamCity`.
Lazily, it is easier to add a step.
But it will cause the fork project to run the action every day

**Comment by RSS1102** [comment]
I will try to see if there is a hook function that only executes within a fixed repo, waiting for my discovery or new ideas.
