### ISSUE TITLE
[⭐ feature]感觉可以多增加一些用户类型组件

### ISSUE THREAD

**Issue by 7836246** [shuimo-design/shuimo-ui#84]
增加类似Badge Avatar 多一些中国风的组件

**Comment by higuaifan** [comment]
感谢您的喜欢，
我们对此这类`基础组件`确实有规划，但是`UI`比较忙，所以推进会慢一点。
如果有明确的某个组件需求的话，可以提出建议，如果合适的话，我们会提高优先级。
