### ISSUE TITLE
[⭐ feature]

### ISSUE THREAD

**Issue by LouisEiermann** [shuimo-design/shuimo-ui#90]
# ⭐ Feature Request

- [x] I have checked that this feature has not already been requested.

## 📢 Describe the feature

> English translation of the documentation

Is there any way you could add completly English translations for international developers using this library?

> 🤝Thanks for your contribution!

**Comment by higuaifan** [comment]
oh! I was just thinking about this this afternoon. Please wait a day or two and I'll get to work on it right away! !
btw, if you are willing, please give us a star, it will be of great help to us.
