### ISSUE TITLE
[🐞 bug]nuxt install

### ISSUE THREAD

**Issue by wanghaisheng** [shuimo-design/shuimo-ui#91]
# 🐞 Bug Report

> 请尽可能使用英文描述问题，或者是提供中英文双语描述（机翻也没有关系），便于后来者检索问题。

**If you are absolutely certain that this is a `bug` and you are able and willing to submit a `PR`, please do so.**

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of the code available.

## 📢 Describe the bug

> A clear and concise description of what the bug is.

> 💻 If the bug is related to UI, please provide some media like screenshots or videos, 
> which will be very helpful for us to locate the problem.

> If it's possible, please provide the minimal reproduction example.

> 🤝Thanks for your contribution!

```package.json
{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "prisma": {
    "seed": "node prisma/seed.js"
  },
  "dependencies": {
    "@nuxtjs/supabase": "^1.2.1",
    "@nuxtjs/tailwindcss": "^6.12.0",
    "@pinia-plugin-persistedstate/nuxt": "^1.2.0",
    "@pinia/nuxt": "^0.5.1",
    "@prisma/client": "^5.13.0",
    "@stripe/stripe-js": "^3.3.0",
    "nuxt": "^3.11.2",
    "nuxt-icon": "^0.6.10",
    "nuxt-lodash": "^2.5.3",
    "pinia": "^2.1.7",
    "prisma": "^5.13.0",
    "shuimo-ui": "0.3.0-alpha.14",
    "stripe": "^15.4.0",
    "vue": "^3.4.21",
    "vue-router": "^4.3.0"
  }
}
```

error ```
$ pnpm dlx module add @shuimo-design/shuimo-ui-nuxt
 WARN  6 deprecated subdependencies found: glob@5.0.15, inflight@1.0.6, resolve-url@0.2.1, source-map-resolve@0.5.3, source-map-url@0.4.1, urix@0.1.0
Packages: +181                                                                                              
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  
Progress: resolved 181, reused 89, downloaded 92, added 181, done
Usage: module <dir>

Options:
  -h, --help     Show help                                             [boolean]
  -v, --version  Show version                                          [boolean]

Too many directories specified.
```

**Comment by higuaifan** [comment]
use this:
``` shell
npx nuxi@latest module add @shuimo-design/shuimo-ui-nuxt
```
doc: [nuxi module add](https://nuxt.com/docs/api/commands/module#nuxi-module-add)
